main: pw.byakuren.weather_plugin.WeatherPlugin
name: BetterWeather
version: 1.0.0
description: Improves minecraft's weather system
load: POSTWORLD
api-version: 1.16

commands:
  forecast:
    description: Check the weather forecast
    permission: betterweather.forecast
  weather_control:
    description: Enable or disable control of the weather in the configured worlds
    permission: betterweater.weather_control
  weather_seed:
    description: Check the weather seed
    permission: betterweather.weather_seed
  reseed:
    description: Pick a new random seed for the weather
    permission: betterweather.reseed
  curworld:
    description: Prints the current world you are in, and whether or not it supports weather
    permission: betterweather.curworld
  nextphase:
    description: Skip to the next weather phase
    permission: betterweather.timeskip

permissions:
  betterweather.forecast:
    default: true
    description: Allows use of /forecast
  betterweather.weather_control:
    default: op
    description: Allows toggling weather control
  betterweather.weather_seed:
    default: op
    description: Allows viewing weather seed
  betterweather.reseed:
    default: op
    description: Allows changing the weather seed
  betterweather.curworld:
    default: true
    description: Allows you to view the name of your current world
  betterweather.timeskip:
    default: op
    description: Allows you to use timeskip commands
